.\"	$NetBSD: wtf.6,v 1.13 2009/05/04 20:37:28 wiz Exp $
.\"
.\" Public Domain
.\"
.Dd December 16, 2012
.Dt WTF 6
.Os
.Sh NAME
.Nm wtf
.Nd translates acronyms for you
.Sh SYNOPSIS
.Nm
.Op Fl f Ar dbfile
.Op Ar is
.Ar acronym Ar ...
.Sh DESCRIPTION
The
.Nm
utility displays the expansion of the acronyms
specified on the command line.
If the acronym is not in any of the acronyms databases,
.Nm
will check to see if the acronym is known by
.Xr apropos 1
or
.Xr xbps-query 8 .
.Pp
If
.Dq is
is specified on the command line, it will be ignored, allowing the
fairly natural
.Dq wtf is WTF
usage.
.Pp
The following options are available:
.Bl -tag -width flag
.It Fl f Ar dbfile
Overrides the default acronym database, bypassing the value of the
.Ev ACRONYMDB
variable.
.El
.Sh ENVIRONMENT
.Bl -tag -width ACRONYMDB
.It Ev ACRONYMDB
The default acronym database may be overridden by setting the
environment variable
.Ev ACRONYMDB
to the name of one or more space-separated file names of
acronym databases.
The files must be in the proper format (acronym[tab]meaning).
.El
.Sh FILES
.Bl -tag -width /usr/share/misc/acronyms.XXXX -compact
.It Pa /usr/share/misc/acronyms
default acronym database.
.It Pa /usr/share/misc/acronyms.comp
computer-related acronym database.
.El
.Sh SEE ALSO
.Xr make 1 ,
.Xr apropos 1 ,
.Xr xbps-query 8 .
.Sh HISTORY
.Nm
first appeared in
.Nx 1.5 ,
and was adapted for Void Linux in 2012.
